const ERROR_BAD_DATA = 400;
const ERROR_UNAUTHORIZED = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_CONFLICT_REQUEST = 409;
const ERROR_DEFAULT = 500;

module.exports = {
  ERROR_BAD_DATA,
  ERROR_NOT_FOUND,
  ERROR_DEFAULT,
  ERROR_UNAUTHORIZED,
  ERROR_CONFLICT_REQUEST,
  ERROR_FORBIDDEN,
};
